#!/usr/bin/expect -f

set timeout 10

set user [lindex $argv 0]
set password [lindex $argv 1]

spawn heroku login

expect "Email: "
send "$user\r";

expect "Password (typing will be hidden): "
send "$password\r";

interact
