# Cliente Telegram
# https://github.com/atipugin/telegram-bot-ruby
gem 'telegram-bot-ruby'

# Binários wkhtmltoimage
# https://github.com/nicholasklick/wkhtmltoimage-binary
gem 'wkhtmltoimage-binary'

# Cria imagens a partir de HTML+CSS
# https://github.com/csquared/IMGKit
gem 'imgkit'

# Codificação HTML
# https://github.com/threedaymonk/htmlentities
gem 'htmlentities'

