# = Redmine configuration file
#
# Each environment has it's own configuration options.  If you are only
# running in production, only the production block needs to be configured.
# Environment specific configuration options override the default ones.
#
# Note that this file needs to be a valid YAML file.
# DO NOT USE TABS! Use 2 spaces instead of tabs for identation.

production:
  delivery_method: :smtp
  smtp_settings:
    address: "smtp.ippuvr.com.br"
    port: 25
    authentication: :plain
    domain: "ippuvr.com.br"
    user_name: redmine@ippuvr.com.br
    password: gledsoncruz@123
